config/routes.rb
Travel::Application.routes.draw do
  authenticated :user do
	root :to => 'home#show'
  end
  root :to => 'home#index'
  devise_for :users
	
  resources :home
  resources :location

end

app/models/locations.rb
class Locations < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :timestamp, :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def create
		print "********************************HERE*************************"
		@location = Locations.new
		@location.latitude = params[:latitude]
		@location.longitude = params[:longitude]
		@location.email = current_user.email
		print "location", @location
		if @location.save!
			flash[:notice] = "Success"
			redirect_to locations_path
		end
	end
	
	def index
		@locations = Locations.all
		
		print "********************************************************"
		print @locations
	end
	
	def show
		@locations = Locations.all
		
		print "********************************************************"
		print @locations
	end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController

	def create
		print "********************************HERE*************************"
		@location = Locations.new
		@location.latitude = params[:latitude]
		@location.longitude = params[:longitude]
		@location.email = current_user.email
		print "location", @location
		if @location.save!
			flash[:notice] = "Success"
			redirect_to location_path
		end
	end
	
	def index
		@locations = Locations.all
		
		print "********************************************************"
		print @locations
	end
	
	def show
		@locations = Locations.all
		
		print "********************************************************"
		print @locations
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/location_helper.rb
module LocationHelper
end

app/views/home/_mainpage.html.erb
<html lang="en">
<head>
	<meta charset="utf-8" content="width=device-width, initial-scale=1.0" name="viewport"></meta>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
</head>
	
<body>
	<p class="btn btn-primary btn-lg" id="location_page"><%= link_to 'Locate', '/location' %></p>
</body>
	
</html>

app/views/home/_topbar.html.erb
<html lang="en">
	

<body>
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">TravelJournal</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

</body>
</html>

app/views/home/create.js.erb
$('#geoLocation').html("<%=h @message.html_safe %>");

app/views/home/index.html.erb
<html lang="en" class="home_html">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">

<body class="home_body">
	<div class = "container form-signin">
	<h2 class="form-signin-heading">Sign in</h2>
	<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
		<p>
			<%= f.email_field :email, :autofocus => true, :placeholder => "Email", :class => "form-control" %>
		</p>

		<div>
			<%= f.password_field :password, :placeholder => "Password", :class => "form-control" %>
		

			<% if devise_mapping.rememberable? -%>
				<div class="checkbox"><%= f.check_box :remember_me%> <%= f.label :remember_me %></div>
			<% end -%>
		</div>

		<p class="text-center"><%= f.submit "Sign in", :class => "btn btn-primary btn-lg"%></p>
	<% end %>

<%= render "devise/shared/links" %>
	</div>
</body>
</html>

app/views/home/show.html.erb
<html lang="en">
<head>
	<meta charset="utf-8" content="width=device-width, initial-scale=1.0" name="viewport"></meta>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
	<%= render 'home/topbar' %>
	<%= render 'home/mainpage' %>
</body>

<script src=""//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/location/create.js.erb
$('#geoLocation').html("<%=h @message.html_safe %>");

app/views/location/show.html.erb
<html lang="en">
<head>
	<meta charset="utf-8" content="width=device-width, initial-scale=1.0" name="viewport"></meta>
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
</head>
	
<body>
	<button class="btn btn-primary btn-lg" id="location_button">locate</button>
	<thead>
		<tr>
			<% if @locations %>
			<th> Latitude </th>
			<th> Longitude </th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% if @locations %>
		<%- @locations.each do |location| %>
			<tr>
			<td> <%= location.latitude %> </td>
			<td> <%= location.longitude %> </td>
			</tr>
		<%- end %>
		<% end %>
	</tbody>

</body>
	
</html>